// Tên tiếng Anh chuẩn theo bản dịch thông dụng hệ thống tài khoản Việt Nam (T76)
export const TEN_ANH: Record<string, string> = {
  '111': 'Cash on hand',
  '1111': 'Vietnamese dong',
  '1112': 'Foreign currencies',
  '1113': 'Monetary gold',
  '112': 'Cash in bank',
  '1121': 'Vietnamese dong',
  '1122': 'Foreign currencies',
  '1123': 'Monetary gold',
  '113': 'Cash in transit',
  '1131': 'Vietnamese dong',
  '1132': 'Foreign currencies',
  '121': 'Trading securities',
  '1211': 'Shares',
  '1212': 'Bonds',
  '1218': 'Other securities and financial instruments',
  '128': 'Held-to-maturity investments',
  '1281': 'Term deposits',
  '1282': 'Bonds',
  '1283': 'Loans',
  '1288': 'Other held-to-maturity investments',
  '131': 'Receivables from customers',
  '133': 'Deductible VAT',
  '1331': 'Deductible VAT on goods and services',
  '1332': 'Deductible VAT on fixed assets',
  '136': 'Internal receivables',
  '1361': 'Operating capital in subordinate units',
  '1362': 'Internal receivables for exchange differences',
  '1363': 'Internal receivables for borrowing costs eligible for capitalisation',
  '1368': 'Other internal receivables',
  '138': 'Other receivables',
  '1381': 'Shortage of assets awaiting resolution',
  '1385': 'Equitisation receivables',
  '1386': 'Pledges, mortgages, collaterals and deposits',
  '1388': 'Other receivables',
  '141': 'Advances',
  '151': 'Goods in transit',
  '152': 'Raw materials',
  '153': 'Tools and supplies',
  '1531': 'Tools and supplies',
  '1532': 'Reusable containers',
  '1533': 'Rented supplies',
  '1534': 'Equipment and spare parts',
  '154': 'Work in progress',
  '155': 'Finished goods',
  '1551': 'Warehoused finished goods',
  '1557': 'Real estate finished goods',
  '156': 'Merchandise',
  '1561': 'Purchasing cost of merchandise',
  '1562': 'Merchandise purchasing expenses',
  '1567': 'Real estate merchandise',
  '157': 'Goods sent on consignment',
  '158': 'Goods in bonded warehouse',
  '161': 'Project expenditures',
  '1611': 'Previous year project expenditures',
  '1612': 'Current year project expenditures',
  '171': 'Repurchase transactions of government bonds',
  '211': 'Tangible fixed assets',
  '2111': 'Buildings and structures',
  '2112': 'Machinery and equipment',
  '2113': 'Vehicles and transmission equipment',
  '2114': 'Management equipment and tools',
  '2115': 'Perennial trees, working and producing animals',
  '2118': 'Other fixed assets',
  '212': 'Finance lease fixed assets',
  '2121': 'Tangible finance lease fixed assets',
  '2122': 'Intangible finance lease fixed assets',
  '213': 'Intangible fixed assets',
  '2131': 'Land use rights',
  '2132': 'Publishing rights',
  '2133': 'Copyrights and patents',
  '2134': 'Trademarks and trade names',
  '2135': 'Software programs',
  '2136': 'Licenses and franchise licenses',
  '2138': 'Other intangible fixed assets',
  '214': 'Depreciation of fixed assets',
  '2141': 'Depreciation of tangible fixed assets',
  '2142': 'Depreciation of finance lease fixed assets',
  '2143': 'Depreciation of intangible fixed assets',
  '2147': 'Depreciation of investment property',
  '217': 'Investment property',
  '221': 'Investments in subsidiaries',
  '222': 'Investments in joint ventures and associates',
  '228': 'Other investments',
  '2281': 'Capital contributions in other entities',
  '2288': 'Other investments',
  '229': 'Provision for asset losses',
  '2291': 'Provision for impairment of trading securities',
  '2292': 'Provision for losses in other entities',
  '2293': 'Provision for doubtful debts',
  '2294': 'Provision for devaluation of inventories',
  '241': 'Construction in progress',
  '2411': 'Procurement of fixed assets',
  '2412': 'Construction in progress',
  '2413': 'Major repairs of fixed assets',
  '242': 'Prepaid expenses',
  '243': 'Deferred tax assets',
  '244': 'Pledges, mortgages, collaterals and deposits paid',
  '331': 'Payables to suppliers',
  '333': 'Taxes and statutory payables',
  '3331': 'VAT payable',
  '33311': 'Output VAT',
  '33312': 'Import VAT',
  '3332': 'Special consumption tax',
  '3333': 'Import and export duties',
  '3334': 'Corporate income tax',
  '3335': 'Personal income tax',
  '3336': 'Natural resource tax',
  '3337': 'Land and housing tax, land rental',
  '3338': 'Environmental protection tax and other taxes',
  '33381': 'Environmental protection tax',
  '33382': 'Other taxes',
  '3339': 'Fees, charges and other payables',
  '334': 'Payables to employees',
  '3341': 'Payables to workers and staff',
  '3348': 'Payables to other laborers',
  '335': 'Accrued expenses',
  '336': 'Internal payables',
  '3361': 'Internal payables for operating capital',
  '3362': 'Internal payables for exchange differences',
  '3363': 'Internal payables for borrowing costs eligible for capitalisation',
  '3368': 'Other internal payables',
  '337': 'Construction contract progress billings',
  '338': 'Other payables',
  '3381': 'Surplus assets awaiting resolution',
  '3382': 'Trade union fees',
  '3383': 'Social insurance',
  '3384': 'Health insurance',
  '3385': 'Equitisation payables',
  '3386': 'Unemployment insurance',
  '3387': 'Unearned revenues',
  '3388': 'Other payables',
  '341': 'Borrowings and finance lease liabilities',
  '3411': 'Borrowings',
  '3412': 'Finance lease liabilities',
  '343': 'Bonds issued',
  '3431': 'Ordinary bonds',
  '3432': 'Convertible bonds',
  '344': 'Pledges, mortgages, collaterals and deposits received',
  '347': 'Deferred tax liabilities',
  '352': 'Provisions payable',
  '3521': 'Provision for product and goods warranties',
  '3522': 'Provision for construction warranties',
  '3523': 'Provision for business restructuring',
  '3524': 'Other provisions payable',
  '353': 'Bonus and welfare funds',
  '3531': 'Bonus fund',
  '3532': 'Welfare fund',
  '3533': 'Welfare fund for fixed assets',
  '3534': 'Management bonus fund',
  '356': 'Science and technology development fund',
  '3561': 'Science and technology development fund',
  '3562': 'Science and technology development fund for fixed assets',
  '357': 'Price stabilization fund',
  '411': 'Owner\'s equity',
  '4111': 'Contributed capital',
  '4112': 'Share premium',
  '4113': 'Convertible bond options',
  '4118': 'Other capital',
  '412': 'Asset revaluation reserve',
  '413': 'Foreign exchange differences',
  '4131': 'Exchange differences on monetary items',
  '4132': 'Exchange differences in pre-operating period',
  '414': 'Development investment fund',
  '417': 'Enterprise reorganization assistance fund',
  '418': 'Other equity funds',
  '419': 'Treasury shares',
  '421': 'Undistributed earnings after tax',
  '4211': 'Prior years undistributed earnings',
  '4212': 'Current year undistributed earnings',
  '441': 'Capital expenditure fund',
  '461': 'Project funds',
  '4611': 'Previous year project funds',
  '4612': 'Current year project funds',
  '466': 'Project funds invested in fixed assets',
  '511': 'Revenue from sales of goods and rendering of services',
  '5111': 'Revenue from merchandise sales',
  '5112': 'Revenue from finished goods sales',
  '5113': 'Revenue from services',
  '5114': 'Revenue from subsidies and pricing support',
  '5117': 'Revenue from investment property',
  '5118': 'Other revenue',
  '515': 'Financial income',
  '521': 'Revenue deductions',
  '5211': 'Trade discounts',
  '5212': 'Sales returns',
  '5213': 'Sales allowances',
  '611': 'Purchases',
  '6111': 'Purchase of raw materials',
  '6112': 'Purchase of merchandise',
  '621': 'Direct raw materials expense',
  '622': 'Direct labour expense',
  '623': 'Machine execution expense',
  '627': 'Manufacturing overhead',
  '6271': 'Workshop staff expense',
  '6272': 'Materials expense',
  '6273': 'Tools and supplies expense',
  '6274': 'Depreciation of fixed assets',
  '6277': 'Outside services expense',
  '6278': 'Other cash expenses',
  '631': 'Manufacturing cost',
  '632': 'Cost of goods sold',
  '635': 'Financial expenses',
  '641': 'Selling expenses',
  '6411': 'Staff expense',
  '6412': 'Materials and packaging expense',
  '6413': 'Tools and supplies expense',
  '6414': 'Depreciation of fixed assets',
  '6415': 'Warranty expense',
  '6417': 'Outside services expense',
  '6418': 'Other cash expenses',
  '642': 'General and administrative expenses',
  '6421': 'Management staff expense',
  '6422': 'Management materials expense',
  '6423': 'Office supplies expense',
  '6424': 'Depreciation of fixed assets',
  '6425': 'Taxes, fees and charges',
  '6426': 'Provision expense',
  '6427': 'Outside services expense',
  '6428': 'Other cash expenses',
  '711': 'Other income',
  '811': 'Other expenses',
  '821': 'Corporate income tax expense',
  '8211': 'Current corporate income tax expense',
  '8212': 'Deferred corporate income tax expense',
  '911': 'Determination of business results',
}
